GRANT CONNECT ON DATABASE auth TO auth_admin;

\c auth

GRANT USAGE ON SCHEMA public TO auth_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO auth_admin;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO auth_admin;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO auth_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO auth_admin;