GRANT ALL PRIVILEGES ON DATABASE auth TO auth_admin;

\c auth

GRANT CREATE ON DATABASE auth TO auth_admin;
GRANT CREATE ON SCHEMA public TO auth_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO auth_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO auth_admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO auth_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO auth_admin;

ALTER DATABASE auth OWNER TO auth_admin;