version: '3.8'
services:
  users_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: users_admin
      POSTGRES_PASSWORD: ${USERS_DB_ADMIN_PASSWORD}
      POSTGRES_DB: users
    volumes:
      - users_db_data:/var/lib/postgresql/data
      - ./users-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  auth_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: ${AUTH_DB_ADMIN_PASSWORD}
      POSTGRES_DB: auth
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  users_db_data:
  auth_db_data: