GRANT CONNECT ON DATABASE users TO users_admin;

\c users

GRANT USAGE ON SCHEMA public TO users_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO users_admin;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO users_admin;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO users_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO users_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO users_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO users_admin;